### ISSUE TITLE
Version is undefined

### ISSUE THREAD

**Issue by Lavadude82** [hi-ashleyj/node-wiimote#15]
I found a report that I have no idea what to do with
/home/iduarte/Downloads/wii-mation/node_modules/node-wiimote/wii.js:284
                                console.log("We are working very hard to support all types of report, so please make sure you have the latest version. Current: " + version);
                                                                                                                                                                    ^

ReferenceError: version is not defined
    at HID.<anonymous> (/home/iduarte/Downloads/wii-mation/node_modules/node-wiimote/wii.js:284:137)
    at HID.emit (node:events:517:28)
    at readFunc (/home/iduarte/Downloads/wii-mation/node_modules/node-hid/nodehid.js:119:22)

Node.js v18.18.2

**Comment by Lavadude82** [comment]
Current Solution : 

```
} else {
				/*console.log("I found a report that I have no idea what to do with");
				console.log("We are working very hard to support all types of report, so please make sure you have the latest version. Current: Not Included Because of Error");
				console.log("If you have the latest version, keep a note of the following information");
				console.log(e);
				console.log("Please send it in as a bug report on git, if there is already data that matches yours just comment on it please!");
				console.log("Alternatively, use the Wiimote documentation on Wiibrew to figure out what is going on and submit that, or fix it and submit a pull request.");
				*/return u.sendData([0x12, 0x00, 0x30]);
			}
		});
```
This will remove the logging, and the version error. The Version won't be known, but it works now :)

**Comment by SweatyCircle439** [comment]
i made a pull request to fix it, tho i don't know if this project is still maintained

**Comment by hi-ashleyj** [comment]
still maintained, bug is fixed by the move to TS but need to get to feature parity before release, plus with extra experience i think this can be laid out better for more rapid development. will get to this over the christmas break but i can also make up issues for tracking if people are interested in supporting the project
